# Define que ao mergear na main será executada a pipe
trigger:
  - main

# Define o tipo de sistema que será construído e executado o projeto
pool:
  vmImage: 'ubuntu-latest'

# Configura as etapas que serão criadas na pipe
steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    packageType: sdk

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release
  displayName: 'Build project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'Docker Hub'
    repository: 'victorsamp/studentcrud:1.0'
    dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)